version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: mainUser
      POSTGRES_PASSWORD: Shimakoo@1385
      POSTGRES_DB: tourism_nahavand
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - turism-nahavand-network
      - nginx-network

  tourism-nahavand-api-nest:
    build: .
    container_name: tourism-nahavand-api-nest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      # Override localhost → postgres service name inside Docker network
      POSTGRES_HOST: postgres
    ports:
      - "4000:4000"
    networks:
      - turism-nahavand-network
      - nginx-network

volumes:
  pgdata:

networks:
  turism-nahavand-network:
    driver: bridge
  nginx-network:
    external: true
